<?php

use Illuminate\Database\Seeder;
use App\Flat;

class FlatsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        // 1

        Flat::create([
            'building_id'     => 1,
            'floor_id'     => 1,
            'label' => '1',
            'residential' => 0,
            'dispozition' => "3",
            'rooms' => 3,
            'size' => 50,
            'type' => 'obchodní',
            'balcony' => 1,
            'heating' => 1,
            'warm_water' => 1,
            'cold_water' => 1,
            'electricity' => 1,
            'electricity_check_first' => '2019-06-20',
            'electricity_check_last' => '2019-08-20',
            'gas' => 1,
            'antena' => 1,
            'EZS' => 1,
            'EPS' => 1,
            'data' => 1,
            'CCTV' => 1,
            'available' => 1,
            'rent' => 40000,
            'fees' => 3000,
        ]);

        Flat::create([
            'building_id'     => 1,
            'floor_id'     => 1,
            'label' => '2',
            'residential' => 0,
            'dispozition' => "3",
            'rooms' => 3,
            'size' => 50,
            'type' => 'obchodní',
            'balcony' => 1,
            'heating' => 1,
            'warm_water' => 1,
            'cold_water' => 1,
            'electricity' => 1,
            'electricity_check_first' => '2019-06-20',
            'electricity_check_last' => '2019-08-20',
            'gas' => 1,
            'antena' => 1,
            'EZS' => 1,
            'EPS' => 1,
            'data' => 1,
            'CCTV' => 1,
            'available' => 1,
            'rent' => 40000,
            'fees' => 3000,
        ]);

        Flat::create([
            'building_id'     => 1,
            'floor_id'     => 1,
            'label' => '3',
            'residential' => 1,
            'dispozition' => "3(kk)",
            'rooms' => 3,
            'size' => 50,
            'type' => 'obytná',
            'balcony' => 1,
            'heating' => 1,
            'warm_water' => 1,
            'cold_water' => 1,
            'electricity' => 1,
            'electricity_check_first' => '2019-06-20',
            'electricity_check_last' => '2019-08-20',
            'gas' => 1,
            'antena' => 1,
            'EZS' => 1,
            'EPS' => 1,
            'data' => 1,
            'CCTV' => 0,
            'available' => 0,
            'rent' => 40000,
            'fees' => 3000,
        ]);

        Flat::create([
            'building_id'     => 1,
            'floor_id'     => 1,
            'label' => '4',
            'residential' => 1,
            'dispozition' => "3(kk)",
            'rooms' => 3,
            'size' => 50,
            'type' => 'obytná',
            'balcony' => 1,
            'heating' => 1,
            'warm_water' => 1,
            'cold_water' => 1,
            'electricity' => 1,
            'electricity_check_first' => '2019-06-20',
            'electricity_check_last' => '2019-08-20',
            'gas' => 1,
            'antena' => 1,
            'EZS' => 1,
            'EPS' => 1,
            'data' => 1,
            'CCTV' => 0,
            'available' => 1,
            'rent' => 40000,
            'fees' => 3000,
        ]);

        // 2

        Flat::create([
            'building_id'     => 1,
            'floor_id'     => 2,
            'label' => '5',
            'residential' => 1,
            'dispozition' => "3(kk)",
            'rooms' => 3,
            'size' => 50,
            'type' => 'obytná',
            'balcony' => 1,
            'heating' => 1,
            'warm_water' => 1,
            'cold_water' => 1,
            'electricity' => 1,
            'electricity_check_first' => '2019-06-20',
            'electricity_check_last' => '2019-08-20',
            'gas' => 1,
            'antena' => 1,
            'EZS' => 1,
            'EPS' => 1,
            'data' => 1,
            'CCTV' => 0,
            'available' => 1,
            'rent' => 40000,
            'fees' => 3000,
        ]);

        Flat::create([
            'building_id'     => 1,
            'floor_id'     => 2,
            'label' => '6',
            'residential' => 1,
            'dispozition' => "3(kk)",
            'rooms' => 3,
            'size' => 50,
            'type' => 'obytná',
            'balcony' => 1,
            'heating' => 1,
            'warm_water' => 1,
            'cold_water' => 1,
            'electricity' => 1,
            'electricity_check_first' => '2019-06-20',
            'electricity_check_last' => '2019-08-20',
            'gas' => 1,
            'antena' => 1,
            'EZS' => 1,
            'EPS' => 1,
            'data' => 1,
            'CCTV' => 0,
            'available' => 1,
            'rent' => 40000,
            'fees' => 3000,
        ]);

        Flat::create([
            'building_id'     => 1,
            'floor_id'     => 2,
            'label' => '7',
            'residential' => 1,
            'dispozition' => "3(kk)",
            'rooms' => 3,
            'size' => 50,
            'type' => 'obytná',
            'balcony' => 1,
            'heating' => 1,
            'warm_water' => 1,
            'cold_water' => 1,
            'electricity' => 1,
            'electricity_check_first' => '2019-06-20',
            'electricity_check_last' => '2019-08-20',
            'gas' => 1,
            'antena' => 1,
            'EZS' => 1,
            'EPS' => 1,
            'data' => 1,
            'CCTV' => 0,
            'available' => 1,
            'rent' => 40000,
            'fees' => 3000,
        ]);

        Flat::create([
            'building_id'     => 1,
            'floor_id'     => 2,
            'label' => '8',
            'residential' => 1,
            'dispozition' => "3(kk)",
            'rooms' => 3,
            'size' => 50,
            'type' => 'obytná',
            'balcony' => 1,
            'heating' => 1,
            'warm_water' => 1,
            'cold_water' => 1,
            'electricity' => 1,
            'electricity_check_first' => '2019-06-20',
            'electricity_check_last' => '2019-08-20',
            'gas' => 1,
            'antena' => 1,
            'EZS' => 1,
            'EPS' => 1,
            'data' => 1,
            'CCTV' => 0,
            'available' => 1,
            'rent' => 40000,
            'fees' => 3000,
        ]);

        // 0

        Flat::create([
            'building_id'     => 1,
            'floor_id'     => 3,
            'label' => '-1',
            'residential' => 0,
            'dispozition' => "1",
            'rooms' => 3,
            'size' => 15,
            'type' => 'technologický',
            'balcony' => 0,
            'heating' => 1,
            'warm_water' => 1,
            'cold_water' => 1,
            'electricity' => 1,
            'electricity_check_first' => '2019-06-20',
            'electricity_check_last' => '2019-08-20',
            'gas' => 1,
            'antena' => 1,
            'EZS' => 1,
            'EPS' => 1,
            'data' => 1,
            'CCTV' => 0,
            'available' => 0,
            'rent' => 35000,
            'fees' => 3500,
        ]);

        Flat::create([
            'building_id'     => 1,
            'floor_id' => 3,
            'label' => '-2',
            'residential' => 0,
            'dispozition' => "1",
            'rooms' => 3,
            'size' => 50,
            'type' => 'skladovací',
            'balcony' => 0,
            'heating' => 1,
            'warm_water' => 1,
            'cold_water' => 1,
            'electricity' => 1,
            'electricity_check_first' => '2019-06-20',
            'electricity_check_last' => '2019-08-20',
            'gas' => 1,
            'antena' => 1,
            'EZS' => 1,
            'EPS' => 1,
            'data' => 1,
            'CCTV' => 1,
            'available' => 0,
            'rent' => 50000,
            'fees' => 4000,
        ]);

        Flat::create([
            'building_id'     => 1,
            'floor_id'     => 3,
            'label' => '-3',
            'residential' => 0,
            'dispozition' => "1",
            'rooms' => 1,
            'size' => 15,
            'type' => 'smíšený',
            'balcony' => 0,
            'heating' => 1,
            'warm_water' => 1,
            'cold_water' => 1,
            'electricity' => 1,
            'electricity_check_first' => '2019-06-20',
            'electricity_check_last' => '2019-08-20',
            'gas' => 1,
            'antena' => 1,
            'EZS' => 1,
            'EPS' => 1,
            'data' => 1,
            'CCTV' => 0,
            'available' => 0,
            'rent' => 45000,
            'fees' => 3500,
        ]);

        Flat::create([
            'building_id'     => 1,
            'floor_id'     => 3,
            'label' => '-4',
            'residential' => 0,
            'dispozition' => "1",
            'rooms' => 1,
            'size' => 15,
            'type' => 'smíšený',
            'balcony' => 0,
            'heating' => 1,
            'warm_water' => 1,
            'cold_water' => 1,
            'electricity' => 1,
            'electricity_check_first' => '2019-06-20',
            'electricity_check_last' => '2019-08-20',
            'gas' => 1,
            'antena' => 1,
            'EZS' => 1,
            'EPS' => 1,
            'data' => 1,
            'CCTV' => 0,
            'available' => 0,
            'rent' => 45000,
            'fees' => 3500,
        ]);
    }
}
